defmodule LinearSDK.Inputs.CustomerUpdateInput do
  @moduledoc ~S'''
  GraphQL input_object `CustomerUpdateInput`.

  _No description._

  ## Summary

  - Kind: `input_object`


  ## Input Fields

  | Name | Type | Default | Deprecated | Description |
  | --- | --- | --- | --- | --- |
  | `domains` | [LinearSDK.Scalars.String!] | `n/a` | No | The domains associated with this customer. |
  | `externalIds` | [LinearSDK.Scalars.String!] | `n/a` | No | The ids of the customers in external systems. |
  | `logoUrl` | LinearSDK.Scalars.String | `n/a` | No | The URL of the customer's logo. |
  | `mainSourceId` | LinearSDK.Scalars.String | `n/a` | No | The main source of the customer, for customers with multiple sources. Must be one of externalIds. |
  | `name` | LinearSDK.Scalars.String | `n/a` | No | The name of the customer. |
  | `ownerId` | LinearSDK.Scalars.String | `n/a` | No | The user who owns the customer. |
  | `revenue` | LinearSDK.Scalars.Int | `n/a` | No | The annual revenue generated by the customer. |
  | `size` | LinearSDK.Scalars.Int | `n/a` | No | The size of the customer. |
  | `slackChannelId` | LinearSDK.Scalars.String | `n/a` | No | The ID of the Slack channel used to interact with the customer. |
  | `statusId` | LinearSDK.Scalars.String | `n/a` | No | The status of the customer. |
  | `tierId` | LinearSDK.Scalars.String | `n/a` | No | The tier of the customer customer. |
  '''
end
