defmodule LinearSDK.Inputs.CustomerUpsertInput do
  @moduledoc ~S'''
  GraphQL input_object `CustomerUpsertInput`.

  _No description._

  ## Summary

  - Kind: `input_object`


  ## Input Fields

  | Name | Type | Default | Deprecated | Description |
  | --- | --- | --- | --- | --- |
  | `domains` | [LinearSDK.Scalars.String!] | `n/a` | No | The domains associated with this customer. |
  | `externalId` | LinearSDK.Scalars.String | `n/a` | No | The id of the customers in external systems. |
  | `id` | LinearSDK.Scalars.String | `n/a` | No | The identifier in UUID v4 format. |
  | `logoUrl` | LinearSDK.Scalars.String | `n/a` | No | The URL of the customer's logo. |
  | `name` | LinearSDK.Scalars.String | `n/a` | No | The name of the customer. |
  | `ownerId` | LinearSDK.Scalars.String | `n/a` | No | The user who owns the customer. |
  | `revenue` | LinearSDK.Scalars.Int | `n/a` | No | The annual revenue generated by the customer. |
  | `size` | LinearSDK.Scalars.Int | `n/a` | No | The size of the customer. |
  | `slackChannelId` | LinearSDK.Scalars.String | `n/a` | No | The ID of the Slack channel used to interact with the customer. |
  | `statusId` | LinearSDK.Scalars.String | `n/a` | No | The status of the customer. |
  | `tierId` | LinearSDK.Scalars.String | `n/a` | No | The tier of the customer. |
  | `tierName` | LinearSDK.Scalars.String | `n/a` | No | The name tier of the customer. Will be created if doesn't exist |
  '''
end
