defmodule LinearSDK.Objects.Customer do
  @moduledoc ~S'''
  GraphQL object `Customer`.

  A customer whose needs will be tied to issues or projects.

  ## Summary

  - Kind: `object`


  ## Relationships

  - Implements: LinearSDK.Interfaces.Node

  ## Fields

  | Name | Type | Arguments | Deprecated | Description |
  | --- | --- | --- | --- | --- |
  | `approximateNeedCount` | LinearSDK.Scalars.Float! | `none` | No | The approximate number of needs of the customer. |
  | `archivedAt` | LinearSDK.Scalars.DateTime | `none` | No | The time at which the entity was archived. Null if the entity has not been archived. |
  | `createdAt` | LinearSDK.Scalars.DateTime! | `none` | No | The time at which the entity was created. |
  | `domains` | [LinearSDK.Scalars.String!]! | `none` | No | The domains associated with this customer. |
  | `externalIds` | [LinearSDK.Scalars.String!]! | `none` | No | The ids of the customers in external systems. |
  | `id` | LinearSDK.Scalars.ID! | `none` | No | The unique identifier of the entity. |
  | `integration` | LinearSDK.Objects.Integration | `none` | No | The integration that manages the Customer. |
  | `logoUrl` | LinearSDK.Scalars.String | `none` | No | The customer's logo URL. |
  | `mainSourceId` | LinearSDK.Scalars.String | `none` | No | The ID of the main source, when a customer has multiple sources. Must be one of externalIds. |
  | `name` | LinearSDK.Scalars.String! | `none` | No | The customer's name. |
  | `needs` | [LinearSDK.Objects.CustomerNeed!]! | `none` | No | Customer needs associated with this customer. |
  | `owner` | LinearSDK.Objects.User | `none` | No | The user who owns the customer. |
  | `revenue` | LinearSDK.Scalars.Int | `none` | No | The annual revenue generated by the customer. |
  | `size` | LinearSDK.Scalars.Float | `none` | No | The size of the customer. |
  | `slackChannelId` | LinearSDK.Scalars.String | `none` | No | The ID of the Slack channel used to interact with the customer. |
  | `slugId` | LinearSDK.Scalars.String! | `none` | No | The customer's unique URL slug. |
  | `status` | LinearSDK.Objects.CustomerStatus! | `none` | No | The current status of the customer. |
  | `tier` | LinearSDK.Objects.CustomerTier | `none` | No | The tier of the customer. |
  | `updatedAt` | LinearSDK.Scalars.DateTime! | `none` | No | The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't |
  | `url` | LinearSDK.Scalars.String! | `none` | No | URL of the customer in Linear. |
  '''
end
