defmodule LinearSDK.Objects.CustomerWebhookPayload do
  @moduledoc ~S'''
  GraphQL object `CustomerWebhookPayload`.

  Payload for a customer webhook.

  ## Summary

  - Kind: `object`


  ## Fields

  | Name | Type | Arguments | Deprecated | Description |
  | --- | --- | --- | --- | --- |
  | `approximateNeedCount` | LinearSDK.Scalars.Float! | `none` | No | The approximate number of needs of the customer. |
  | `archivedAt` | LinearSDK.Scalars.String | `none` | No | The time at which the entity was archived. |
  | `createdAt` | LinearSDK.Scalars.String! | `none` | No | The time at which the entity was created. |
  | `domains` | [LinearSDK.Scalars.String!]! | `none` | No | The domains associated with this customer. |
  | `externalIds` | [LinearSDK.Scalars.String!]! | `none` | No | The ids of the customers in external systems. |
  | `id` | LinearSDK.Scalars.String! | `none` | No | The ID of the entity. |
  | `logoUrl` | LinearSDK.Scalars.String | `none` | No | The customer's logo URL. |
  | `mainSourceId` | LinearSDK.Scalars.String | `none` | No | The ID of the main source, when a customer has multiple sources. Must be one of externalIds. |
  | `name` | LinearSDK.Scalars.String! | `none` | No | The name of the customer. |
  | `ownerId` | LinearSDK.Scalars.String | `none` | No | The ID of the user who owns the customer. |
  | `revenue` | LinearSDK.Scalars.Float | `none` | No | The annual revenue generated by the customer. |
  | `size` | LinearSDK.Scalars.Float | `none` | No | The size of the customer. |
  | `slackChannelId` | LinearSDK.Scalars.String | `none` | No | The ID of the Slack channel used to interact with the customer. |
  | `slugId` | LinearSDK.Scalars.String! | `none` | No | The customer's unique URL slug. |
  | `status` | LinearSDK.Objects.CustomerStatusChildWebhookPayload | `none` | No | The customer status. |
  | `statusId` | LinearSDK.Scalars.String | `none` | No | The ID of the customer status. |
  | `tier` | LinearSDK.Objects.CustomerTierChildWebhookPayload | `none` | No | The customer tier. |
  | `tierId` | LinearSDK.Scalars.String | `none` | No | The ID of the customer tier. |
  | `updatedAt` | LinearSDK.Scalars.String! | `none` | No | The time at which the entity was updated. |
  | `url` | LinearSDK.Scalars.String! | `none` | No | The URL of the customer. |
  '''
end
