defmodule LinearSDK.Objects.Draft do
  @moduledoc ~S'''
  GraphQL object `Draft`.

  A general purpose draft. Used for comments, project updates, etc.

  ## Summary

  - Kind: `object`


  ## Relationships

  - Implements: LinearSDK.Interfaces.Node

  ## Fields

  | Name | Type | Arguments | Deprecated | Description |
  | --- | --- | --- | --- | --- |
  | `anchor` | LinearSDK.Scalars.String | `none` | No | [INTERNAL] Allows for multiple drafts per entity (currently constrained to Pull Requests). |
  | `archivedAt` | LinearSDK.Scalars.DateTime | `none` | No | The time at which the entity was archived. Null if the entity has not been archived. |
  | `bodyData` | LinearSDK.Scalars.JSON! | `none` | No | The text content as a Prosemirror document. |
  | `createdAt` | LinearSDK.Scalars.DateTime! | `none` | No | The time at which the entity was created. |
  | `customerNeed` | LinearSDK.Objects.CustomerNeed | `none` | No | The customer need that this draft is referencing. |
  | `data` | LinearSDK.Scalars.JSONObject | `none` | No | Additional properties for the draft. |
  | `id` | LinearSDK.Scalars.ID! | `none` | No | The unique identifier of the entity. |
  | `initiative` | LinearSDK.Objects.Initiative | `none` | No | The initiative for which this is a draft comment or initiative update. |
  | `initiativeUpdate` | LinearSDK.Objects.InitiativeUpdate | `none` | No | The initiative update for which this is a draft comment. |
  | `isAutogenerated` | LinearSDK.Scalars.Boolean! | `none` | Yes | Whether the draft was autogenerated for the user. |
  | `issue` | LinearSDK.Objects.Issue | `none` | No | The issue for which this is a draft comment. |
  | `parentComment` | LinearSDK.Objects.Comment | `none` | No | The comment for which this is a draft comment reply. |
  | `post` | LinearSDK.Objects.Post | `none` | No | The post for which this is a draft comment. |
  | `project` | LinearSDK.Objects.Project | `none` | No | The project for which this is a draft comment or project update. |
  | `projectUpdate` | LinearSDK.Objects.ProjectUpdate | `none` | No | The project update for which this is a draft comment. |
  | `team` | LinearSDK.Objects.Team | `none` | No | The team for which this is a draft post. |
  | `updatedAt` | LinearSDK.Scalars.DateTime! | `none` | No | The last time at which the entity was meaningfully updated. This is the same as the creation time if the entity hasn't |
  | `user` | LinearSDK.Objects.User! | `none` | No | The user who created the draft. |
  | `wasLocalDraft` | LinearSDK.Scalars.Boolean! | `none` | No | [INTERNAL] Whether the draft was ported from a local draft. |
  '''
end
